// fechapartidos.js
/* const datosPartidosFixture = [
    { id: 1, fecha: "Jueves 11 de junio", hora: "16:00", local: "México", visitante: "Sudáfrica", grupo: "Grupo A", estadio: "Estadio Ciudad de México", goles_local: null, goles_visitante: null },
    { id: 2, fecha: "Jueves 11 de junio", hora: "23:00", local: "República de Corea", visitante: "Chequia", grupo: "Grupo A", estadio: "Guadalajara", goles_local: null, goles_visitante: null },
    { id: 3, fecha: "Viernes 12 de junio", hora: "16:00", local: "Canadá", visitante: "Bosnia y Herzegovina", grupo: "Grupo B", estadio: "Toronto", goles_local: null, goles_visitante: null },
    { id: 4, fecha: "Viernes 12 de junio", hora: "22:00", local: "Estados Unidos", visitante: "Paraguay", grupo: "Grupo D", estadio: "Los Ángeles", goles_local: null, goles_visitante: null }
    // ... Resto de los partidos de la primera fase
]; */

// mundial2026_completo.js
const datosPartidosFixture = [
  {
    id: 1,
    fecha: "2026-06-11",
    dia: "Jueves",
    hora: "16:00",
    grupo: "A",
    local: "México",
    visitante: "Sudáfrica",
    estadio: "Estadio Ciudad de México",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 2,
    fecha: "2026-06-11",
    dia: "Jueves",
    hora: "23:00",
    grupo: "A",
    local: "Corea del Sur",
    visitante: "República Checa",
    estadio: "Guadalajara",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 3,
    fecha: "2026-06-12",
    dia: "Viernes",
    hora: "16:00",
    grupo: "B",
    local: "Canadá",
    visitante: "Bosnia",
    estadio: "Toronto",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 4,
    fecha: "2026-06-12",
    dia: "Viernes",
    hora: "22:00",
    grupo: "D",
    local: "Estados Unidos",
    visitante: "Paraguay",
    estadio: "Los Ángeles",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 5,
    fecha: "2026-06-13",
    dia: "Sábado",
    hora: "16:00",
    grupo: "B",
    local: "Qatar",
    visitante: "Suiza",
    estadio: "San Francisco",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 6,
    fecha: "2026-06-13",
    dia: "Sábado",
    hora: "19:00",
    grupo: "C",
    local: "Brasil",
    visitante: "Marruecos",
    estadio: "Nueva York/Nueva Jersey",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 7,
    fecha: "2026-06-13",
    dia: "Sábado",
    hora: "22:00",
    grupo: "C",
    local: "Haití",
    visitante: "Escocia",
    estadio: "Boston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 8,
    fecha: "2026-06-14",
    dia: "Domingo",
    hora: "01:00",
    grupo: "D",
    local: "Australia",
    visitante: "Turquía",
    estadio: "Vancouver",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 9,
    fecha: "2026-06-14",
    dia: "Domingo",
    hora: "14:00",
    grupo: "E",
    local: "Alemania",
    visitante: "Curazao",
    estadio: "Houston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 10,
    fecha: "2026-06-14",
    dia: "Domingo",
    hora: "17:00",
    grupo: "F",
    local: "Países Bajos",
    visitante: "Japón",
    estadio: "Dallas",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 11,
    fecha: "2026-06-14",
    dia: "Domingo",
    hora: "20:00",
    grupo: "E",
    local: "Costa de Marfil",
    visitante: "Ecuador",
    estadio: "Filadelfia",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 12,
    fecha: "2026-06-14",
    dia: "Domingo",
    hora: "23:00",
    grupo: "F",
    local: "Suecia",
    visitante: "Túnez",
    estadio: "Monterrey",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 13,
    fecha: "2026-06-15",
    dia: "Lunes",
    hora: "13:00",
    grupo: "H",
    local: "España",
    visitante: "Cabo Verde",
    estadio: "Atlanta",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 14,
    fecha: "2026-06-15",
    dia: "Lunes",
    hora: "16:00",
    grupo: "G",
    local: "Bélgica",
    visitante: "Egipto",
    estadio: "Seattle",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 15,
    fecha: "2026-06-15",
    dia: "Lunes",
    hora: "19:00",
    grupo: "H",
    local: "Arabia Saudita",
    visitante: "Uruguay",
    estadio: "Miami",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 16,
    fecha: "2026-06-15",
    dia: "Lunes",
    hora: "22:00",
    grupo: "G",
    local: "Irán",
    visitante: "Nueva Zelanda",
    estadio: "Los Ángeles",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 17,
    fecha: "2026-06-16",
    dia: "Martes",
    hora: "16:00",
    grupo: "I",
    local: "Francia",
    visitante: "Senegal",
    estadio: "Nueva York/Nueva Jersey",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 18,
    fecha: "2026-06-16",
    dia: "Martes",
    hora: "19:00",
    grupo: "I",
    local: "Irak",
    visitante: "Noruega",
    estadio: "Boston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 19,
    fecha: "2026-06-16",
    dia: "Martes",
    hora: "22:00",
    grupo: "J",
    local: "Argentina",
    visitante: "Argelia",
    estadio: "Kansas City",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 20,
    fecha: "2026-06-17",
    dia: "Miércoles",
    hora: "01:00",
    grupo: "J",
    local: "Austria",
    visitante: "Jordania",
    estadio: "San Francisco",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 21,
    fecha: "2026-06-17",
    dia: "Miércoles",
    hora: "14:00",
    grupo: "K",
    local: "Portugal",
    visitante: "RD Congo",
    estadio: "Houston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 22,
    fecha: "2026-06-17",
    dia: "Miércoles",
    hora: "17:00",
    grupo: "L",
    local: "Inglaterra",
    visitante: "Croacia",
    estadio: "Dallas",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 23,
    fecha: "2026-06-17",
    dia: "Miércoles",
    hora: "20:00",
    grupo: "L",
    local: "Ghana",
    visitante: "Panamá",
    estadio: "Toronto",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 24,
    fecha: "2026-06-17",
    dia: "Miércoles",
    hora: "23:00",
    grupo: "K",
    local: "Uzbekistán",
    visitante: "Colombia",
    estadio: "Ciudad de México",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 25,
    fecha: "2026-06-18",
    dia: "Jueves",
    hora: "13:00",
    grupo: "A",
    local: "República Checa",
    visitante: "Sudáfrica",
    estadio: "Atlanta",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 26,
    fecha: "2026-06-18",
    dia: "Jueves",
    hora: "16:00",
    grupo: "B",
    local: "Suiza",
    visitante: "Bosnia",
    estadio: "Los Ángeles",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 27,
    fecha: "2026-06-18",
    dia: "Jueves",
    hora: "19:00",
    grupo: "B",
    local: "Canadá",
    visitante: "Qatar",
    estadio: "Vancouver",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 28,
    fecha: "2026-06-18",
    dia: "Jueves",
    hora: "22:00",
    grupo: "A",
    local: "México",
    visitante: "Corea del Sur",
    estadio: "Guadalajara",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 29,
    fecha: "2026-06-19",
    dia: "Viernes",
    hora: "16:00",
    grupo: "D",
    local: "Estados Unidos",
    visitante: "Australia",
    estadio: "Seattle",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 30,
    fecha: "2026-06-19",
    dia: "Viernes",
    hora: "19:00",
    grupo: "C",
    local: "Escocia",
    visitante: "Marruecos",
    estadio: "Boston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 31,
    fecha: "2026-06-19",
    dia: "Viernes",
    hora: "22:00",
    grupo: "C",
    local: "Brasil",
    visitante: "Haití",
    estadio: "Filadelfia",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 32,
    fecha: "2026-06-20",
    dia: "Sábado",
    hora: "01:00",
    grupo: "D",
    local: "Turquía",
    visitante: "Paraguay",
    estadio: "San Francisco",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 33,
    fecha: "2026-06-20",
    dia: "Sábado",
    hora: "14:00",
    grupo: "F",
    local: "Países Bajos",
    visitante: "Suecia",
    estadio: "Houston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 34,
    fecha: "2026-06-20",
    dia: "Sábado",
    hora: "17:00",
    grupo: "E",
    local: "Alemania",
    visitante: "Costa de Marfil",
    estadio: "Toronto",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 35,
    fecha: "2026-06-20",
    dia: "Sábado",
    hora: "21:00",
    grupo: "E",
    local: "Ecuador",
    visitante: "Curazao",
    estadio: "Kansas City",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 36,
    fecha: "2026-06-21",
    dia: "Domingo",
    hora: "01:00",
    grupo: "F",
    local: "Túnez",
    visitante: "Japón",
    estadio: "Monterrey",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 37,
    fecha: "2026-06-21",
    dia: "Domingo",
    hora: "13:00",
    grupo: "H",
    local: "España",
    visitante: "Arabia Saudita",
    estadio: "Atlanta",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 38,
    fecha: "2026-06-21",
    dia: "Domingo",
    hora: "16:00",
    grupo: "G",
    local: "Bélgica",
    visitante: "Irán",
    estadio: "Los Ángeles",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 39,
    fecha: "2026-06-21",
    dia: "Domingo",
    hora: "19:00",
    grupo: "H",
    local: "Uruguay",
    visitante: "Cabo Verde",
    estadio: "Miami",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 40,
    fecha: "2026-06-21",
    dia: "Domingo",
    hora: "22:00",
    grupo: "G",
    local: "Nueva Zelanda",
    visitante: "Egipto",
    estadio: "Vancouver",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 41,
    fecha: "2026-06-22",
    dia: "Lunes",
    hora: "14:00",
    grupo: "J",
    local: "Argentina",
    visitante: "Austria",
    estadio: "Dallas",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 42,
    fecha: "2026-06-22",
    dia: "Lunes",
    hora: "18:00",
    grupo: "I",
    local: "Francia",
    visitante: "Irak",
    estadio: "Filadelfia",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 43,
    fecha: "2026-06-22",
    dia: "Lunes",
    hora: "21:00",
    grupo: "I",
    local: "Noruega",
    visitante: "Senegal",
    estadio: "Nueva York/Nueva Jersey",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 44,
    fecha: "2026-06-23",
    dia: "Martes",
    hora: "00:00",
    grupo: "J",
    local: "Jordania",
    visitante: "Argelia",
    estadio: "San Francisco",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 45,
    fecha: "2026-06-23",
    dia: "Martes",
    hora: "14:00",
    grupo: "K",
    local: "Portugal",
    visitante: "Uzbekistán",
    estadio: "Houston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 46,
    fecha: "2026-06-23",
    dia: "Martes",
    hora: "17:00",
    grupo: "L",
    local: "Inglaterra",
    visitante: "Ghana",
    estadio: "Boston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 47,
    fecha: "2026-06-23",
    dia: "Martes",
    hora: "20:00",
    grupo: "L",
    local: "Panamá",
    visitante: "Croacia",
    estadio: "Toronto",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 48,
    fecha: "2026-06-23",
    dia: "Martes",
    hora: "23:00",
    grupo: "K",
    local: "Colombia",
    visitante: "RD Congo",
    estadio: "Guadalajara",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 49,
    fecha: "2026-06-24",
    dia: "Miércoles",
    hora: "16:00",
    grupo: "B",
    local: "Suiza",
    visitante: "Canadá",
    estadio: "Vancouver",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 50,
    fecha: "2026-06-24",
    dia: "Miércoles",
    hora: "16:00",
    grupo: "B",
    local: "Bosnia",
    visitante: "Qatar",
    estadio: "Seattle",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 51,
    fecha: "2026-06-24",
    dia: "Miércoles",
    hora: "19:00",
    grupo: "C",
    local: "Escocia",
    visitante: "Brasil",
    estadio: "Miami",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 52,
    fecha: "2026-06-24",
    dia: "Miércoles",
    hora: "19:00",
    grupo: "C",
    local: "Marruecos",
    visitante: "Haití",
    estadio: "Atlanta",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 53,
    fecha: "2026-06-24",
    dia: "Miércoles",
    hora: "22:00",
    grupo: "A",
    local: "República Checa",
    visitante: "México",
    estadio: "Ciudad de México",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 54,
    fecha: "2026-06-24",
    dia: "Miércoles",
    hora: "22:00",
    grupo: "A",
    local: "Sudáfrica",
    visitante: "Corea del Sur",
    estadio: "Monterrey",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 55,
    fecha: "2026-06-25",
    dia: "Jueves",
    hora: "17:00",
    grupo: "E",
    local: "Ecuador",
    visitante: "Alemania",
    estadio: "Nueva York/Nueva Jersey",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 56,
    fecha: "2026-06-25",
    dia: "Jueves",
    hora: "17:00",
    grupo: "E",
    local: "Curazao",
    visitante: "Costa de Marfil",
    estadio: "Filadelfia",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 57,
    fecha: "2026-06-25",
    dia: "Jueves",
    hora: "20:00",
    grupo: "F",
    local: "Túnez",
    visitante: "Países Bajos",
    estadio: "Kansas City",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 58,
    fecha: "2026-06-25",
    dia: "Jueves",
    hora: "20:00",
    grupo: "F",
    local: "Japón",
    visitante: "Suecia",
    estadio: "Dallas",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 59,
    fecha: "2026-06-25",
    dia: "Jueves",
    hora: "23:00",
    grupo: "D",
    local: "Turquía",
    visitante: "Estados Unidos",
    estadio: "Los Ángeles",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 60,
    fecha: "2026-06-25",
    dia: "Jueves",
    hora: "23:00",
    grupo: "D",
    local: "Paraguay",
    visitante: "Australia",
    estadio: "San Francisco",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 61,
    fecha: "2026-06-26",
    dia: "Viernes",
    hora: "16:00",
    grupo: "I",
    local: "Noruega",
    visitante: "Francia",
    estadio: "Boston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 62,
    fecha: "2026-06-26",
    dia: "Viernes",
    hora: "16:00",
    grupo: "I",
    local: "Senegal",
    visitante: "Irak",
    estadio: "Toronto",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 63,
    fecha: "2026-06-26",
    dia: "Viernes",
    hora: "21:00",
    grupo: "H",
    local: "Uruguay",
    visitante: "España",
    estadio: "Guadalajara",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 64,
    fecha: "2026-06-26",
    dia: "Viernes",
    hora: "21:00",
    grupo: "H",
    local: "Cabo Verde",
    visitante: "Arabia Saudita",
    estadio: "Houston",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 65,
    fecha: "2026-06-27",
    dia: "Sábado",
    hora: "00:00",
    grupo: "G",
    local: "Nueva Zelanda",
    visitante: "Bélgica",
    estadio: "Vancouver",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 66,
    fecha: "2026-06-27",
    dia: "Sábado",
    hora: "00:00",
    grupo: "G",
    local: "Egipto",
    visitante: "Irán",
    estadio: "Seattle",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 67,
    fecha: "2026-06-27",
    dia: "Sábado",
    hora: "18:00",
    grupo: "L",
    local: "Panamá",
    visitante: "Inglaterra",
    estadio: "Nueva York/Nueva Jersey",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 68,
    fecha: "2026-06-27",
    dia: "Sábado",
    hora: "18:00",
    grupo: "L",
    local: "Croacia",
    visitante: "Ghana",
    estadio: "Filadelfia",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 69,
    fecha: "2026-06-27",
    dia: "Sábado",
    hora: "20:30",
    grupo: "K",
    local: "Colombia",
    visitante: "Portugal",
    estadio: "Miami",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 70,
    fecha: "2026-06-27",
    dia: "Sábado",
    hora: "20:30",
    grupo: "K",
    local: "RD Congo",
    visitante: "Uzbekistán",
    estadio: "Atlanta",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 71,
    fecha: "2026-06-27",
    dia: "Sábado",
    hora: "23:00",
    grupo: "J",
    local: "Jordania",
    visitante: "Argentina",
    estadio: "Dallas",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
  {
    id: 72,
    fecha: "2026-06-27",
    dia: "Sábado",
    hora: "23:00",
    grupo: "J",
    local: "Argelia",
    visitante: "Austria",
    estadio: "Kansas City",
    golesLocal: null,
    golesVisitante: null,
    jugado: false,
  },
];